openapi: 3.0.3
info:
  title: EmporioLambda BE
  description: Queste sono le OpenAPI per EmporioLambda
  version: 0.1.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/swexception4/OpenAPI/0.1.0
  - description: serverless offline
    url: http://localhost:4000/dev/
paths:
  /categories:
    $ref: "categories/openapi/categories.yml"
  /categories/{id}:
    $ref: "categories/openapi/categoriesByID.yml"
  
  /products:
    $ref: "products/openapi/products.yml"
  /products/{id}:
    $ref: "products/openapi/productsByID.yml"

  /taxes:
    $ref: "taxes/openapi/taxes.yml"
  /taxes/{id}:
    $ref: "taxes/openapi/taxesByID.yml"

  /cart:
    $ref: "carts/openapi/cart.yml"
  /cart/product/{id}:
    $ref: "carts/openapi/cartByID.yml"

  /addresses:
    $ref: "addresses/openapi/addresses.yml"
  /addresses/{id}:
    $ref: "addresses/openapi/addressesByID.yml"

  /checkout:
    $ref: "checkout/openapi/checkout.yml"
  
  /orders:
    $ref: "orders/openapi/orders.yml"
  /orders/{id}:
    $ref: "orders/openapi/ordersByID.yml"

  /users/check/{token}:
    $ref: "users/openapi/checkJWT.yml"
  /users/customers:
    $ref: "users/openapi/customers.yml"
  /users/customers/{username}:
    $ref: "users/openapi/customersByID.yml"

tags:
  - name: products
    description: "API for products"

  - name: categories
    description: "API for categories"

  - name: addresses
    description: "API for addresses"

  - name: checkout
    description: "API for checkout"

  - name: cart
    description: "API for cart"

  - name: taxes
    description: "API for taxes"

  - name: users
    description: "API for users"

  - name: orders
    description: "API for orders"
