name: build OpenAPI
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: script
        run: ${GITHUB_WORKSPACE}/buildOpenAPI.sh --install
        shell: bash
